language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator10.0
script:
- set -o pipefail
- travis_retry xcodebuild -workspace BeyovaJSON.xcworkspace -scheme "BeyovaJSON iOS" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
- travis_retry xcodebuild -workspace BeyovaJSON.xcworkspace -scheme "BeyovaJSON macOS" build-for-testing test | xcpretty
